### ISSUE TITLE
Where put "Action" records?

### ISSUE THREAD

**Issue by Tardo** [OCA/odoo-community.org#31]
Where is the best place for "action" records? 
inside '\_view/s?.xml' to have all related to one model in the same place? all in a separate actions.xml file? In the same .xml file that uses the action (for example menus.xml)? Where does one consider appropriate?

OCA Guidelines about "actions": https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#security-view-and-action

**Comment by pedrobaeza** [comment]
I usually place at the end of the view file, but no special guideline. Maybe we can normalize that.

**Comment by Tardo** [comment]
Who cares? closed!
