### ISSUE TITLE
About ID names...

### ISSUE THREAD

**Issue by Tardo** [OCA/odoo-community.org#32]
OCA Guidelines tell us that for naming id for a view you need use "<model_name>\_view\_<view_type>"...
https://www.odoo.com/documentation/11.0/reference/guidelines.html#naming-xml-id

What happens when you have two "form" views for the same model?

**Comment by pedrobaeza** [comment]
Well, that's a general rule, and it should be that way because you don't normally have 2 forms views for the same model. But in that case, you can use an extra suffix. If you think it's relevant for being noted on the guidelines, you can propose a PR with the wording for that.
