### ISSUE TITLE
Order of module results doesn't help

### ISSUE THREAD

**Issue by Yajo** [OCA/odoo-community.org#46]
See, I've made a search for the module `l10n_es_toponyms` and these are the results:

![Captura de pantalla de 2020-01-29 08-20-12](https://user-images.githubusercontent.com/973709/73339302-61a20580-4270-11ea-8e33-0e2f66210080.png)

As you can see, the most important result appears last. This is something that keeps bugging me around. It seems like the search also matches when a module depends on the one you're searching on any version, which could help or could just clutter the results without need when you know what you're searching. When there are several pages of results, it's fastidious.

For example, [the module `l10n_es_location_nuts` appears there because in v8 it depended on `l10n_es_toponyms`](https://github.com/OCA/l10n-spain/blob/7c5cab54465eabbeacf570350595979a6db44231/l10n_es_location_nuts/__openerp__.py#L19), but it's unrelated in higher versions. Also that relation is not clear when you see the module page.

The situation for `l10n_es_partner` is pretty similar.

So, my suggestion is that we should reorder modules like this:

1. Module that matches exactly the query (`l10n_es_toponyms`).
1. Modules that match partially the query (`l10n_es_toponyms_region`).
1. Modules where some dependency matches the query.

The 3rd one could even be a checkbox "search dependencies", which could be enabled or disabled by default. It could add a GET param to the URL, so bookmark users can just choose to (dis/en)able it directly.

**Comment by pedrobaeza** [comment]
This must go in https://github.com/OCA/apps-store

**Comment by yajo** [comment]
Can you move the issue? I think the option exists for repo admins.
