### ISSUE TITLE
Contribution guide mixes syntax

### ISSUE THREAD

**Issue by Yajo** [OCA/odoo-community.org#47]
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst is mixing syntax from MD and RST.

Where is this deployed? Is it really working? :thinking:

**Comment by pedrobaeza** [comment]
It is used just as is in the GitHub viewer. I see everything correct, but you can propose a PR for making it homogeneous.

**Comment by Yajo** [comment]
Take a closer look:

![imagen](https://user-images.githubusercontent.com/973709/82210530-2bfc5780-9907-11ea-881b-af54bc2821ee.png)

**Comment by pedrobaeza** [comment]
Ah, OK, then let's got to RST everywhere...
