### ISSUE TITLE
issue with odoo-community apps download after upgrade

### ISSUE THREAD

**Issue by farazda1** [OCA/odoo-community.org#59]
![image](https://user-images.githubusercontent.com/10349579/103073616-5c188100-45e1-11eb-8a93-03c41d2562c1.png)

**Comment by pedrobaeza** [comment]
Fixed already in https://github.com/OCA/apps-store/commit/42a333937c9380ba69cb07a27aa7d48a3681aa1c, but not deployed.

@sbidoul can you deploy it?

**Comment by sbidoul** [comment]
This is now deployed. Thanks for the fix!

**Comment by sbidoul** [comment]
It seems there is another download issue, though: https://github.com/OCA/apps-store/issues/78
