### ISSUE TITLE
QUESTION: Is pep80 necessary today?

### ISSUE THREAD

**Issue by igallart** [OCA/odoo-community.org#65]
I have doubts about the purpose of continuing to limit the lines to 80 characters. At the time someone explained to me that it was because of the small old terminals and to be able to have the maximum information on the screen, but honestly I don't think anyone will be programming on such small screens in the year 2021. I think 120 characters as Odoo does would be fine, but I would like to know more opinions. Thanks.

**Comment by pedrobaeza** [comment]
I think you remember half of the explanation: it's not only for small terminal (which is still valid, as there are many ways to access code). But the main reason is that when having such length, you keep good visual and postural ergonomics, and allow you to do side by side diff.

Note that now the limit is not strict 80, but relaxed one (up to 88) that is done automatically by black.

**Comment by igallart** [comment]
Thanks Pedro, although I think that a little more length would not lose the advantages that you expose. On the other hand, the 88 characters are appreciated, I did not know this detail.
