### ISSUE TITLE
Broken link in guidelines

### ISSUE THREAD

**Issue by SirTakobi** [OCA/odoo-community.org#72]
## Module
n/a

## Describe the bug
The link shown below
![image](https://user-images.githubusercontent.com/101628000/212923374-f7014978-7be4-4e5f-847d-1049f612c992.png)

(in https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message) is broken and should be rendered as a link.

## To Reproduce
**Affected versions**:
n/a

1. Go to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message
2. Open the link that should list the tags

**Expected behavior**
Land in https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#tag-and-module-name

**Additional context**
I'd be happy to propose the change myself, but looks like I cannot contribute to the wiki

**Comment by pedrobaeza** [comment]
This is not wiki, but a regular file in git, so you can propose a PR.
